<!DOCTYPE html>
<html lang="en">
<head>
<!--head-->
<?php  readfile(dirname(__FILE__) ."./../include/head.php"); ?>					
<!--head end-->
    <style>
        .scrollbox {
          poisition: relative;
          width: 100%;
          height: 400px;
          margin: 20px auto;
          padding: 10px;
          background-color: #fff;
          overflow: scroll;
          box-shadow:0 2px 10px rgba(#000,.5);
          @include box-sizing(border-box);
        }

        // スクロールバー全体
        .scrollbox::-webkit-scrollbar {
            width:10px;
            background:#D8EAFF;
        }
        // 横スクロールバー全体
        .scrollbox::-webkit-scrollbar:horizontal {
            height:10px;
        }
        
        // スクロールバー上下左右末端のボタン
        .scrollbox::-webkit-scrollbar-button {
            width:10px;
            height:10px;
            background:#D8EAFF;
        }
        // ドラッグするツマミ部分
        .scrollbox::-webkit-scrollbar-thumb {
            background:#D8EAFF;
            border-radius: 10px;
            box-shadow: none;
        }
        // 右下角部分
        .scrollbox::-webkit-scrollbar-corner {
            background:#D8EAFF;
        }
    </style>		
</head>
<body>
    <div class="wrapper">	
<!--sidebar-->
<?php  readfile(dirname(__FILE__) ."./../include/side.php"); ?>					
<!--sidebar end-->		
        <div class="main-panel">	
			<!--nav　インクルード　-->
			<?php  readfile(dirname(__FILE__) ."./../include/nav.php"); ?>
			<!--nav　インクルード　end-->						
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">詳細ページ2ch</h4>
                                <p class="category">こちらのページは詳細ページです。</p>
                            </div>
                            <div class="content">
                            <?php 
							$id = $_GET[id];
							echo "飛んできたID：".$id;
							//TestMapper_details.php→routes.phpから$dataをオブジェクトとして渡し、クラスの関数getTests_details($id)読み込み							
							?>
							 <table class="table table-hover table-striped">
                                        <thead>
                                            <th>num : uuid</th>
											<th>block</th>
											<th>削除</th>			
                                        </thead>					
                                        <tbody>
										<?php $details = $data->ch2_info_details($id); ?>
										<?php foreach($details as $test): ?>
										  <tr>
											  
												<td style="width:10px"  class="text-center">
												<?=$test['num'] ?>
												:
												<?=$test['uuid'] ?></td>
												<td style="width:100px"  class="text-left">
													<div style="text-align: center">
													<form action ="" method ="post">
														<textarea name="content" rows="3" cols="50" style="vertical-align: middle"><?=$test['block'] ?></textarea>
														<input type="hidden" value="<?=$test['id'] ?>" name="id_up">
														<input type="hidden" value="<?=$test['num'] ?>" name="num_up">
														<input type = "submit" class="btn btn-primary" value ="更新" name="up">
													</form>
													</div>
													</td>
											  　　<td>
													<form action ="" method ="post">
														<input type="hidden" value="<?=$test['id'] ?>" name="id_del">
														<input type="hidden" value="<?=$test['num'] ?>" name="num_del">
														<input type = "submit" class="btn btn-primary" value ="削除">
													</form>
												</td>
												<td>
												<?php
												//現在のページのURLえを取得
												$url = (empty($_SERVER["HTTPS"]) ? "http://" : "https://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];
												var_dump($url);	
												
												//update ボタンが押された場合
												(int)$id_up = $_POST["id_up"];
												(int)$num_up =  $_POST["num_up"];
												$block = $_POST["content"];
																								
												//削除ボタンが押された時　カラムを削除する
												(int)$id_del = $_POST["id_del"]; 
												(int)$num_del = $_POST["num_del"];
												
												//空白じゃない時を実行しないと、タイトルページから詳細ページに移行する時エラー起こる
												//なぜなら初期がnullの為である。その為エラーが起きる。
												if(!empty($id_del) && !empty($num_del)){
												
												$details = $data->ch2_delete($id_del,$num_del);
												
												//削除関数実行と共に、更新を行う
												header('Location:'.$url.'');
												exit();
												
												//更新ボタンが押された時、関数実行
												}else if($_POST["up"]){
													
												$details = $data->ch2_update($id_up,$num_up,$block);
												
												//削除関数実行と共に、更新を行う
												header('Location:'.$url.'');
												exit();
												
												
												}else{
												//何もしないで終了
												
												}
												?>
												
												
												</td>
											  
										  </tr>
										<?php endforeach; ?>
                                        </tbody>
                                    </table>
							
							
							
                                                 
                                
                            <div class="row">
                                <div class="col-md-2 col-md-offset-0">
                                <a href="/slim3/sample/public/book_api_sample" class="btn btn-primary">一つ前に戻る</span></a>
                                </div>
                            </div>
			
			
            <footer class="footer">
					<!--copywrite-->
					<?php  readfile(dirname(__FILE__) ."./../include/copywrite.php"); ?>					
					<!--copywrite end--> 	
            </footer>
        </div>
    </div>
</body>
</body>
<!--core_js-->
<?php  readfile(dirname(__FILE__) ."./../include/core_js.php"); ?>					
<!--core_js end-->		
</html>
